Embedded object constraints
bigladder/lattice pull request #29
Opened 2023-06-05 12:44 UTC by tanaya-bigladder

This branch has already merged the 232-updates branch.
In addition, it includes 3 separate changes: 1. the schema translation Python uses pathlib instead of os.path, 2. exceptions in translation pieces propagate properly to the interface, 3. source schema are first parsed into a new object-type-keyed data structure to make JSON translation flow better.

2023-06-09 19:06 UTC, nealkruis requested changes

2023-06-09 19:06 UTC, nealkruis commented on examples/fan_spec/schema/RS0006.schema.yaml
> +      Data Type: "{PerformanceMapDrive}"
Looks like you missed some...

2023-06-09 19:06 UTC, nealkruis commented on examples/fan_spec/schema/RS0006.schema.yaml
>  PerformanceMapDrive:
☝🏻

2023-06-09 19:06 UTC, nealkruis commented on examples/fan_spec/schema/RS0007.schema.yaml
> +      Data Type: "{PerformanceMapDrive}"
☝🏻

2023-06-09 19:06 UTC, nealkruis commented on examples/fan_spec/schema/RS0007.schema.yaml
> +PerformanceMapDrive:
☝🏻

2023-06-09 19:06 UTC, nealkruis commented on examples/lookup_table/schema/LookupTable.schema.yaml
> +LookupTableTemplate:
❤️

2023-06-26 18:26 UTC, tanaya-bigladder commented
Oops, fixed now.

2023-10-31 21:15 UTC, nealkruis commented
@tanaya-mankad, is this PR now obsolete?

2023-10-31 21:21 UTC, closed without merging

2023-10-31 21:21 UTC, tanaya-mankad commented
PR is closed; I'll make sure the branch has nothing left I want to merge and then delete it as well.